/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2018-03-10 18:32:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registrar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");


    /*String usuario = (String) request.getSession().getAttribute("usuario");
    if (null == request.getSession().getAttribute("usuario")) {
        response.sendRedirect("login_user.jsp");
    } else {
        System.out.print("ingreso al a app");
    }*/


      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("    <link type='text/css' rel=\"stylesheet\" href=\"../lib/bootstrap.css\" >\n");
      out.write("    <link rel=\"stylesheet\" href=\"../lib/jquery-ui.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"../lib/leaflet.css\" />\n");
      out.write("    <!--[if lte IE 8]>\n");
      out.write("        <link rel=\"stylesheet\" href=\"../lib/leaflet.ie.css\" />\n");
      out.write("    <![endif]-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"../lib/jquery.ptTimeSelect.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/styles.css\" />\n");
      out.write("\n");
      out.write("    <!--CSS para Localizacion-->\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../lib/location/L.Control.Locate.css\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "templates/header.jsp", out, false);
      out.write("\n");
      out.write("        <div id=\"map\" style=\"height: 100%\"></div>\n");
      out.write("        <div class=\"left\">\n");
      out.write("            <a id=\"geojsonLayer\"   href=\"#\" ></a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div id=\"modal\">\n");
      out.write("            <div id=\"popover\" class=\"modal container hide fade\" tabindex=\"-1\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                <form  id=\"formulario\" class=\"modal-body content span6\"  method=\"post\"  action=\"");
      out.print(request.getContextPath());
      out.write("/SRegistrar\" enctype=\"multipart/form-data\" >\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\n");
      out.write("\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"span4\">Registrar Como:</div>\n");
      out.write("                    <div class=\"span4\">\n");
      out.write("                        <div class=\"well\"> \n");
      out.write("                            <input type=\"radio\" name=\"reg_como\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idusuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('-');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" checked>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" &nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("                            <input type=\"radio\" name=\"reg_como\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idusuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("-Anonimo\" > Anonimo<br>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"span4\">Tipo de Incidente o Crimen <span class=\"obligatorio\">*</span></div>\n");
      out.write("                    <div class=\"span4\">\n");
      out.write("                        <select name='tipo' id='tipo' align=\"left\" >\n");
      out.write("\n");
      out.write("                            <option value='Robo'>Robo</option>\n");
      out.write("                            <option value='Agresión'>Agresión</option>                                                    \n");
      out.write("                            <option value='Accidente'>Accidente</option>\n");
      out.write("                            <option value='Violencia Familiar'>Violencia Familiar</option>\n");
      out.write("                            <option value='Otros Incidentes'>Otros Incidentes</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"span4\">Fecha <span class=\"obligatorio\">*</span></div>\n");
      out.write("                    <div class=\"span4\"> <input type=\"text\" name=\"fecha\" value=\"\"  id=\"fecha\" style=\"width:400px\" placeholder=\"Haga click para mostrarla la Fecha\" >\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"span4\">Hora <span class=\"obligatorio\">*</span></div>\n");
      out.write("                    <div class=\"span4\"> <input type=\"text\" name=\"hora\" value=\"\"  id=\"hora\" style=\"width:400px\"  placeholder=\"Haga click para mostrarla Hora\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"span4\">Descripción <span class=\"obligatorio\">*</span></div>\n");
      out.write("                    <div class=\"span4\">\n");
      out.write("                        <textarea name=\"descripcion\" rows=\"4\" cols=\"75\"  id=\"descripcion\" style=\"width:400px\" placeholder=\"Ingrese la descripcion del incidente\"></textarea>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"span4\">Direcion/Referencia</div>\n");
      out.write("                    <div class=\"span4\">\n");
      out.write("                        <textarea name=\"direccion\" rows=\"2\" cols=\"75\"  id=\"direcion\" style=\"width:400px\" placeholder=\"Ingrese la direccion exacta o la referencia\"></textarea>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row latlong\">\n");
      out.write("                    <div class=\"span4\">Latitud <span class=\"obligatorio\">*</span></div>\n");
      out.write("                    <div class=\"span4\">\n");
      out.write("                        <input type=\"text\" name=\"latitud\" value=\"\"  id=\"latitud\" placeholder=\"click en el Mapa\" style=\"width:400px\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"span4\">Longitud <span class=\"obligatorio\">*</span> </div>\n");
      out.write("                    <div class=\"span4\">\n");
      out.write("                        <input type=\"text\" name=\"longitud\"  id=\"longitud\" placeholder=\"click en el Mapa\" style=\"width:400px\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"span4\">Imagen del incidente Ocurrido<span class=\"obligatorio\">(Opcional)</span></div>\n");
      out.write("                    <div class=\"span4\">\n");
      out.write("                        <input type=\"file\" name=\"imagen\"   id=\"imagen\"/>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <br>\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\" id=\"button\">  Registrar</button>\n");
      out.write("\n");
      out.write("                <button type=\"button\" data-dismiss=\"modal\" class=\"btn \">Cancelar</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"#popover\"  class=\"click\"  data-toggle=\"modal\"></a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"../lib/jquery-1.8.2.js\"></script>\n");
      out.write("<script src=\"../lib/jquery-ui.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../lib/jquery.ptTimeSelect.js\"></script>\n");
      out.write("<script src=\"../lib/leaflet.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../lib/bootstrap.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../lib/jquery.ptTimeSelect.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../lib/location/L.Control.Locate.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/global.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/app.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/form.js\"></script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
