/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2018-03-10 18:53:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class estadisticas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Estadisticas de Incidencias</title>\n");
      out.write("    </head>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "plantillas/styles.jspf", out, false);
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "plantillas/header.jspf", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!---Estadisticas-->\n");
      out.write("    <div class=\"container\" style=\"margin-top: 150px\">\n");
      out.write("        <div class=\"row-fluid\">\n");
      out.write("            <div class=\"span6 well\">\n");
      out.write("                <div id=\"est_mes\"></div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"span6 well\">\n");
      out.write("                <div id=\"est_crimen\"></div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row-fluid\">\n");
      out.write("            <div class=\"span5\"><h4 style=\"color: #ffffff\">Visualizar estadisticas por tipo de Incidente :</h4></div>\n");
      out.write("            <div class=\"span7\">\n");
      out.write("                <select name='tipo' id='tipo' align=\"left\">                    \n");
      out.write("                    <option value='robo'>Robo</option>\n");
      out.write("                    <option value='agresion'>Agresión</option>                                                    \n");
      out.write("                    <option value='accidente'>Accidente</option>\n");
      out.write("                    <option value='violencia_familiar'>Violencia Familiar</option>\n");
      out.write("                    <option value='otros'>Otros Incidentes</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row-fluid\">\n");
      out.write("            <div class=\"span3\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"span6 well\">\n");
      out.write("                <div id=\"tipo_incidente\">\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"span3\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div><!--/row-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"footer\">\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <script src=\"lib/jquery-1.8.2.js\"></script>\n");
      out.write("    <script src=\"lib/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"lib/underscore-min.js\"></script>\n");
      out.write("    <script src=\"http://localhost:8080/appdel/SCifras_total_crimen\"></script>\n");
      out.write("    <script src=\"http://localhost:8080/appdel/SCifras_total_mes\"></script>\n");
      out.write("    <script src=\"http://localhost:8080/appdel/SCifras_robo\"></script>\n");
      out.write("    <script src=\"http://localhost:8080/appdel/SCifras_agresion\"></script>\n");
      out.write("    <script src=\"http://localhost:8080/appdel/SCifras_accidente\"></script>\n");
      out.write("    <script src=\"http://localhost:8080/appdel/SCifras_violencia_familiar\"></script>\n");
      out.write("    <script src=\"http://localhost:8080/appdel/SCifras_otros_incidentes\"></script>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.google.com/jsapi\"></script>\n");
      out.write("    <script src=\"js/estadisticas.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
